"""Reason codes and the `primary_reason_code` selection rule (02 §6).

The family of a code is declared here rather than parsed from its prefix: the
canonical vocabulary does not spell families into the strings (`INPUT_*` is
represented by `MISSING_REQUIRED_FIELD`, `TIME_*` by `READY_AFTER_CUTOFF`).
Deriving the family from text would silently misfile every one of them.
"""

from __future__ import annotations

from enum import IntEnum


class Family(IntEnum):
    """02 §6.1 priority. Lower wins.

    INPUT_ > TIME_ > TERMINAL_ > DIMENSION_/WEIGHT_ > RESOURCE_ > CAPACITY_ > ALTERNATIVE_
    """

    INPUT = 0
    TIME = 1
    TERMINAL = 2
    DIMENSION_WEIGHT = 3
    RESOURCE = 4
    CAPACITY = 5
    ALTERNATIVE = 6


# Input
MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
INVALID_TIME_RANGE = "INVALID_TIME_RANGE"

# Time
READY_AFTER_CUTOFF = "READY_AFTER_CUTOFF"
DUE_TIME_EXCEEDED = "DUE_TIME_EXCEEDED"

# Terminal
TERMINAL_NOT_COMPATIBLE = "TERMINAL_NOT_COMPATIBLE"
TERMINAL_NOT_ON_SERVICE_ROUTE = "TERMINAL_NOT_ON_SERVICE_ROUTE"

# Dimension / weight
TUNNEL_HEIGHT_EXCEEDED = "TUNNEL_HEIGHT_EXCEEDED"
ROUTE_WIDTH_EXCEEDED = "ROUTE_WIDTH_EXCEEDED"
ROUTE_WEIGHT_EXCEEDED = "ROUTE_WEIGHT_EXCEEDED"
SLOT_HEIGHT_EXCEEDED = "SLOT_HEIGHT_EXCEEDED"
SLOT_WIDTH_EXCEEDED = "SLOT_WIDTH_EXCEEDED"
SLOT_LENGTH_EXCEEDED = "SLOT_LENGTH_EXCEEDED"
SLOT_WEIGHT_EXCEEDED = "SLOT_WEIGHT_EXCEEDED"
WAGON_WEIGHT_EXCEEDED = "WAGON_WEIGHT_EXCEEDED"

# Resource
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
WAGON_UNAVAILABLE = "WAGON_UNAVAILABLE"
SLOT_UNAVAILABLE = "SLOT_UNAVAILABLE"
SLOT_TAG_NOT_SUPPORTED = "SLOT_TAG_NOT_SUPPORTED"
NO_ELIGIBLE_SLOT = "NO_ELIGIBLE_SLOT"

# Capacity
CAPACITY_CONFLICT = "CAPACITY_CONFLICT"

# Alternative
ALTERNATIVE_AVAILABLE = "ALTERNATIVE_AVAILABLE"
ALTERNATIVE_REQUIRES_FORBIDDEN_CHANGE = "ALTERNATIVE_REQUIRES_FORBIDDEN_CHANGE"
ALTERNATIVE_NOT_REQUIRED = "ALTERNATIVE_NOT_REQUIRED"
NO_FEASIBLE_ALTERNATIVE = "NO_FEASIBLE_ALTERNATIVE"

# Sentinel for a clean assignment: a state marker, not a violation (02 §6.1).
ASSIGNED = "ASSIGNED"

FAMILY_BY_CODE: dict[str, Family] = {
    MISSING_REQUIRED_FIELD: Family.INPUT,
    INVALID_TIME_RANGE: Family.INPUT,
    READY_AFTER_CUTOFF: Family.TIME,
    DUE_TIME_EXCEEDED: Family.TIME,
    TERMINAL_NOT_COMPATIBLE: Family.TERMINAL,
    TERMINAL_NOT_ON_SERVICE_ROUTE: Family.TERMINAL,
    TUNNEL_HEIGHT_EXCEEDED: Family.DIMENSION_WEIGHT,
    ROUTE_WIDTH_EXCEEDED: Family.DIMENSION_WEIGHT,
    ROUTE_WEIGHT_EXCEEDED: Family.DIMENSION_WEIGHT,
    SLOT_HEIGHT_EXCEEDED: Family.DIMENSION_WEIGHT,
    SLOT_WIDTH_EXCEEDED: Family.DIMENSION_WEIGHT,
    SLOT_LENGTH_EXCEEDED: Family.DIMENSION_WEIGHT,
    SLOT_WEIGHT_EXCEEDED: Family.DIMENSION_WEIGHT,
    WAGON_WEIGHT_EXCEEDED: Family.DIMENSION_WEIGHT,
    SERVICE_UNAVAILABLE: Family.RESOURCE,
    WAGON_UNAVAILABLE: Family.RESOURCE,
    SLOT_UNAVAILABLE: Family.RESOURCE,
    SLOT_TAG_NOT_SUPPORTED: Family.RESOURCE,
    NO_ELIGIBLE_SLOT: Family.RESOURCE,
    CAPACITY_CONFLICT: Family.CAPACITY,
    ALTERNATIVE_AVAILABLE: Family.ALTERNATIVE,
    ALTERNATIVE_REQUIRES_FORBIDDEN_CHANGE: Family.ALTERNATIVE,
    ALTERNATIVE_NOT_REQUIRED: Family.ALTERNATIVE,
    NO_FEASIBLE_ALTERNATIVE: Family.ALTERNATIVE,
}


def select_primary(codes: list[str]) -> str | None:
    """The single code shown to the operator.

    Earliest family wins; ties inside a family break on the code string so the
    engine and the independent validator always agree (02 §6.1).
    """
    if not codes:
        return None
    return min(codes, key=lambda code: (FAMILY_BY_CODE[code], code))
